/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela.de.captura;

import app.Alerta;
import app.InfoPc;
import inovacao.Inovacao;
import app.InserirMetrica;
import app.LogGenerator;
import app.Looca;
import inovacao.Inovacao;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Window;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import models.UserLogin;
import org.json.JSONObject;
import org.springframework.jdbc.core.JdbcTemplate;
import sql.Conection;

/**
 *
 * @author Rainha Katarine I
 */
public class TelaDeCaptura extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCaptura
     */
    public TelaDeCaptura() {
        Inovacao in = new Inovacao();
        initComponents();
        setLocation(850, 450);

        jButtonCancel.setVisible(false);
        jButtonRebootNow.setVisible(false);
        jButtonRebootTen.setVisible(false);

        new Timer().scheduleAtFixedRate(new TimerTask() {

            public void run() {
                exibirDados();
            }
        }, 0, 10000);
        new Timer().scheduleAtFixedRate(new TimerTask() {

            public void run() {
                try {
                    if (in.verificarData()) {
                        exibirReinicio();
                    } else {
                        jPanelDataScreen.setVisible(true);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }, 0, 10000);
        
         new Timer().scheduleAtFixedRate(new TimerTask() {

            public void run() {
                Alerta alert = new Alerta();
                
                alert.alertaRede();
                alert.alertaRam();
                alert.alertaCpu();
                alert.alertaMemoria();

            }
        }, 0, 10000);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPanelDataScreen = new javax.swing.JPanel();
        jLabelTextData = new javax.swing.JLabel();
        jLabelTextData1 = new javax.swing.JLabel();
        jLabelTextData2 = new javax.swing.JLabel();
        jLabelTextData3 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelXbutton = new javax.swing.JLabel();
        jLabelMinimazingButton = new javax.swing.JLabel();
        jButtonRebootNow = new javax.swing.JButton();
        jButtonRebootTen = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBackground.setBackground(new java.awt.Color(25, 118, 211));

        jPanelDataScreen.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTextData.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTextData.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelTextData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelTextData1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTextData1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelTextData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelTextData2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTextData2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelTextData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelTextData3.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTextData3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelTextData3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelDataScreenLayout = new javax.swing.GroupLayout(jPanelDataScreen);
        jPanelDataScreen.setLayout(jPanelDataScreenLayout);
        jPanelDataScreenLayout.setHorizontalGroup(
            jPanelDataScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTextData1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabelTextData2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextData3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDataScreenLayout.setVerticalGroup(
            jPanelDataScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTextData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTextData1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTextData2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTextData3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Captura de Dados em Andamento");

        jLabelXbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelXbutton.setForeground(new java.awt.Color(255, 255, 255));
        jLabelXbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelXbutton.setText("X");
        jLabelXbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelXbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelXbuttonMouseClicked(evt);
            }
        });

        jLabelMinimazingButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMinimazingButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimazingButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimazingButton.setText("-");
        jLabelMinimazingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMinimazingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimazingButtonMouseClicked(evt);
            }
        });

        jButtonRebootNow.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRebootNow.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRebootNow.setText("REINICIAR");
        jButtonRebootNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRebootNowActionPerformed(evt);
            }
        });

        jButtonRebootTen.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRebootTen.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRebootTen.setText("ADIAR");
        jButtonRebootTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRebootTenActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("CANCELAR");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelMinimazingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelXbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(76, 76, 76))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jPanelDataScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRebootTen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRebootNow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelXbutton)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelMinimazingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelTitle)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelDataScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonRebootNow, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRebootTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButtonRebootNow.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelXbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelXbuttonMouseClicked
        try {
            LogGenerator.generateLog("Usuario deslogado.");
            LogGenerator.generateLog("Encerrando captura de dados.");
        } catch (IOException ex) {
            Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jLabelXbuttonMouseClicked

    private void jLabelMinimazingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimazingButtonMouseClicked
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor((Component) evt.getSource());

        // Minimiza a janela
        if (window instanceof Frame) {
            Frame frame = (Frame) window;
            frame.setExtendedState(Frame.ICONIFIED);
        }
    }//GEN-LAST:event_jLabelMinimazingButtonMouseClicked

    private void jButtonRebootNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRebootNowActionPerformed
        // TODO add your handling code here

        try {
            jButtonCancel.setVisible(false);
            jButtonRebootNow.setVisible(false);
            jButtonRebootTen.setVisible(false);
            jPanelDataScreen.setVisible(true);

            Conection conexao = new Conection();
            JdbcTemplate con = conexao.getConnection();
            InfoPc infoPc = new InfoPc();
            Inovacao in = new Inovacao();
            String setor = in.setor();
            String hostname = infoPc.hostName();

            con.update("update [dbo].[historicoReiniciar] "
                    + "set tempoReiniciar = 0 "
                    + "where fkComputador = ?;", hostname);

            JSONObject json = new JSONObject();
            json.put("text", "Reinicio direto realizado \n"
                    + "\nHostname:" + hostname + "\n"
                    + "Setor:" + setor);

            slack.Slack.sendMessage(json);

            inovacao.TesteInovacao.main();
        } catch (IOException ex) {
            Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRebootNowActionPerformed

    private void jButtonRebootTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRebootTenActionPerformed
        try {
            // TODO add your handling code here:
            jButtonCancel.setVisible(false);
            jButtonRebootNow.setVisible(false);
            jButtonRebootTen.setVisible(false);
            jPanelDataScreen.setVisible(true);

            TimeUnit.SECONDS.sleep(600);

            Conection conexao = new Conection();
            JdbcTemplate con = conexao.getConnection();
            InfoPc infoPc = new InfoPc();
            String hostname = infoPc.hostName();
            Inovacao in = new Inovacao();
            String setor = in.setor();

            JSONObject json = new JSONObject();
            json.put("text", "Reinicio adiado realizado \n"
                    + "\nHostname:" + hostname + "\n"
                    + "Setor:" + setor);

            con.update("update [dbo].[historicoReiniciar] "
                    + "set tempoReiniciar = 0 "
                    + "where fkComputador = ?;", hostname);

            slack.Slack.sendMessage(json);

            inovacao.TesteInovacao.main();
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRebootTenActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:

        try {
            jButtonCancel.setVisible(false);
            jButtonRebootNow.setVisible(false);
            jButtonRebootTen.setVisible(false);
            jPanelDataScreen.setVisible(true);

            Conection conexao = new Conection();
            JdbcTemplate con = conexao.getConnection();
            InfoPc infoPc = new InfoPc();
            String hostname = infoPc.hostName();
            Inovacao in = new Inovacao();
            String setor = in.setor();

            JSONObject json = new JSONObject();
            json.put("text", "Reinicio cancelado \n"
                    + "\nHostname:" + hostname + "\n"
                    + "Setor:" + setor);

            slack.Slack.sendMessage(json);

            con.update("update [dbo].[historicoReiniciar] "
                    + "set tempoReiniciar = 0 "
                    + "where fkComputador = ?;", hostname);
        } catch (IOException ex) {
            Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCaptura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCaptura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCaptura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCaptura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCaptura().setVisible(true);
            }
        });
    }

    public void exibirDados() {
        try {
            LogGenerator.generateLog("Enviando dados...");
        } catch (IOException ex) {
            Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
        }
        InserirMetrica im = new InserirMetrica();

        List teste = im.inserirMetrica();

        String insert1 = teste.get(0).toString();
        String insert2 = teste.get(1).toString();
        String insert3 = teste.get(2).toString();
        String insert4 = teste.get(3).toString();

        jLabelTextData.setText(insert1);
        jLabelTextData1.setText(insert2);
        jLabelTextData2.setText(insert3);
        jLabelTextData3.setText(insert4);
    }

    public void exibirReinicio() {
        try {
            LogGenerator.generateLog("Precisa reiniciar");
        } catch (IOException ex) {
            Logger.getLogger(TelaDeCaptura.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("Deu o tempo");
        jButtonCancel.setVisible(true);
        jButtonRebootNow.setVisible(true);
        jButtonRebootTen.setVisible(true);
        jPanelDataScreen.setVisible(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRebootNow;
    private javax.swing.JButton jButtonRebootTen;
    private javax.swing.JLabel jLabelMinimazingButton;
    private javax.swing.JLabel jLabelTextData;
    private javax.swing.JLabel jLabelTextData1;
    private javax.swing.JLabel jLabelTextData2;
    private javax.swing.JLabel jLabelTextData3;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelXbutton;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelDataScreen;
    // End of variables declaration//GEN-END:variables
}
